reimport_hourly_statistics:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: greenchoice
    start_date:
      required: true
      example: "2026-03-25"
      selector:
        date: {}
